spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/bill_service_database
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /bills
  port: 8082